API,Error
paddle_amp_auto_cast.py,"Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_amp_auto_cast.py"", line 3, in <module>
    conv2d = paddle.nn.Conv2D(3, 2, 3, bias_attr=False)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\conv.py"", line 687, in __init__
    super(Conv2D, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\conv.py"", line 157, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_amp_decorate.py,"Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_amp_decorate.py"", line 5, in <module>
    model = paddle.nn.Conv2D(3, 2, 3, bias_attr=False)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\conv.py"", line 687, in __init__
    super(Conv2D, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\conv.py"", line 157, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_amp_GradScaler.py,"Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_amp_GradScaler.py"", line 3, in <module>
    model = paddle.nn.Conv2D(3, 2, 3, bias_attr=True)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\conv.py"", line 687, in __init__
    super(Conv2D, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\conv.py"", line 157, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_callbacks_EarlyStopping.py,"Cache file C:\Users\phalt\.cache\paddle\dataset\mnist\train-images-idx3-ubyte.gz not found, downloading https://dataset.bj.bcebos.com/mnist/train-images-idx3-ubyte.gz 
Begin to download

Download finished
Cache file C:\Users\phalt\.cache\paddle\dataset\mnist\train-labels-idx1-ubyte.gz not found, downloading https://dataset.bj.bcebos.com/mnist/train-labels-idx1-ubyte.gz 
Begin to download

Download finished
Cache file C:\Users\phalt\.cache\paddle\dataset\mnist\t10k-images-idx3-ubyte.gz not found, downloading https://dataset.bj.bcebos.com/mnist/t10k-images-idx3-ubyte.gz 
Begin to download

Download finished
Cache file C:\Users\phalt\.cache\paddle\dataset\mnist\t10k-labels-idx1-ubyte.gz not found, downloading https://dataset.bj.bcebos.com/mnist/t10k-labels-idx1-ubyte.gz 
Begin to download

Download finished
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_callbacks_EarlyStopping.py"", line 17, in <module>
    net = LeNet()
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\vision\models\lenet.py"", line 50, in __init__
    self.features = nn.Sequential(nn.Conv2D(1, 6, 3, stride=1, padding=1),
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\conv.py"", line 687, in __init__
    super(Conv2D, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\conv.py"", line 157, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_callbacks_LRScheduler.py,"Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_callbacks_LRScheduler.py"", line 14, in <module>
    lenet = paddle.vision.models.LeNet()
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\vision\models\lenet.py"", line 50, in __init__
    self.features = nn.Sequential(nn.Conv2D(1, 6, 3, stride=1, padding=1),
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\conv.py"", line 687, in __init__
    super(Conv2D, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\conv.py"", line 157, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_callbacks_ModelCheckpoint.py,"Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_callbacks_ModelCheckpoint.py"", line 15, in <module>
    lenet = paddle.vision.models.LeNet()
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\vision\models\lenet.py"", line 50, in __init__
    self.features = nn.Sequential(nn.Conv2D(1, 6, 3, stride=1, padding=1),
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\conv.py"", line 687, in __init__
    super(Conv2D, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\conv.py"", line 157, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_callbacks_ProgBarLogger.py,"Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_callbacks_ProgBarLogger.py"", line 15, in <module>
    lenet = paddle.vision.models.LeNet()
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\vision\models\lenet.py"", line 50, in __init__
    self.features = nn.Sequential(nn.Conv2D(1, 6, 3, stride=1, padding=1),
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\conv.py"", line 687, in __init__
    super(Conv2D, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\conv.py"", line 157, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_callbacks_ReduceLROnPlateau.py,"Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_callbacks_ReduceLROnPlateau.py"", line 14, in <module>
    net = LeNet()
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\vision\models\lenet.py"", line 50, in __init__
    self.features = nn.Sequential(nn.Conv2D(1, 6, 3, stride=1, padding=1),
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\conv.py"", line 687, in __init__
    super(Conv2D, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\conv.py"", line 157, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_callbacks_VisualDL.py,"Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_callbacks_VisualDL.py"", line 15, in <module>
    net = paddle.vision.models.LeNet()
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\vision\models\lenet.py"", line 50, in __init__
    self.features = nn.Sequential(nn.Conv2D(1, 6, 3, stride=1, padding=1),
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\conv.py"", line 687, in __init__
    super(Conv2D, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\conv.py"", line 157, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_DataParallel.py,"C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\parallel.py:173: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  warnings.warn(
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_DataParallel.py"", line 33, in <module>
    model = SimpleNet()
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_DataParallel.py"", line 24, in __init__
    self.linear = paddle.nn.Linear(2, 2)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\common.py"", line 160, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_device_IPUPlace.py,"E0330 19:54:29.148988  7132 place.cc:643] Cannot use IPU because you didn't install IPU version PaddlePaddle.
If you want to use IPU, please try to install IPU version PaddlePaddle by: pip install paddlepaddle*
If you only have CPU, please change IPUPlace to be CPUPlace().
"
paddle_device_MLUPlace.py,"E0330 20:49:35.322165 12768 place.cc:710] Cannot use MLU because you have installed CPU/GPU/... version PaddlePaddle.
If you want to use MLU, please try to install MLU version PaddlePaddle by: pip install paddlepaddle-mlu
If you only have CPU, please change MLUPlace(0) to be CPUPlace().
"
paddle_device_XPUPlace.py,"E0330 20:49:44.985078 24528 place.cc:425] Cannot use XPU because you have installed CPU/GPU version PaddlePaddle.
If you want to use XPU, please try to install XPU version PaddlePaddle by: pip install paddlepaddle-xpu
If you only have CPU, please change XPUPlace(0) to be CPUPlace().
"
paddle_distributed_alltoall.py,"C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\parallel.py:173: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  warnings.warn(
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_alltoall.py"", line 13, in <module>
    dist.alltoall([data1, data2], out_tensor_list)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 1276, in alltoall
    group = _get_default_group() if group is None else group
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 125, in _get_default_group
    assert is_initialized(), (
AssertionError: Call paddle.distributed.init_parallel_env first to initialize the distributed environment.
"
paddle_distributed_alltoall_single.py,"C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\parallel.py:173: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  warnings.warn(
W0330 20:50:45.597551  2436 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.1, Runtime API Version: 11.2
W0330 20:50:45.603554  2436 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_alltoall_single.py"", line 14, in <module>
    dist.alltoall_single(data, output)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 1419, in alltoall_single
    group = _get_default_group() if group is None else group
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 125, in _get_default_group
    assert is_initialized(), (
AssertionError: Call paddle.distributed.init_parallel_env first to initialize the distributed environment.
"
paddle_distributed_all_gather.py,"C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\parallel.py:173: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  warnings.warn(
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_all_gather.py"", line 11, in <module>
    dist.all_gather(tensor_list, data)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 946, in all_gather
    group = _get_default_group() if group is None else group
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 125, in _get_default_group
    assert is_initialized(), (
AssertionError: Call paddle.distributed.init_parallel_env first to initialize the distributed environment.
"
paddle_distributed_all_gather_object.py,"C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\parallel.py:173: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  warnings.warn(
W0330 20:51:00.209426 21196 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.1, Runtime API Version: 11.2
W0330 20:51:00.215423 21196 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_all_gather_object.py"", line 11, in <module>
    dist.all_gather_object(object_list, obj)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 1093, in all_gather_object
    all_gather(list_len_of_tensor, len_of_tensor, group)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 946, in all_gather
    group = _get_default_group() if group is None else group
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 125, in _get_default_group
    assert is_initialized(), (
AssertionError: Call paddle.distributed.init_parallel_env first to initialize the distributed environment.
"
paddle_distributed_all_reduce.py,"C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\parallel.py:173: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  warnings.warn(
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_all_reduce.py"", line 10, in <module>
    dist.all_reduce(data)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\communication\all_reduce.py"", line 61, in all_reduce
    return stream.all_reduce(tensor,
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\communication\stream\all_reduce.py"", line 112, in all_reduce
    return _all_reduce_in_dygraph(tensor, op, group, sync_op,
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\communication\stream\all_reduce.py"", line 25, in _all_reduce_in_dygraph
    group = _get_global_group() if group is None else group
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\communication\group.py"", line 86, in _get_global_group
    raise RuntimeError(""The global group is not initialized."")
RuntimeError: The global group is not initialized.
"
paddle_distributed_barrier.py,"C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\parallel.py:173: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  warnings.warn(
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_barrier.py"", line 6, in <module>
    paddle.distributed.barrier()
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 279, in barrier
    group = _get_default_group() if group is None else group
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 125, in _get_default_group
    assert is_initialized(), (
AssertionError: Call paddle.distributed.init_parallel_env first to initialize the distributed environment.
"
paddle_distributed_broadcast.py,"C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\parallel.py:173: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  warnings.warn(
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_broadcast.py"", line 10, in <module>
    dist.broadcast(data, src=1)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 685, in broadcast
    group = _get_default_group() if group is None else group
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 125, in _get_default_group
    assert is_initialized(), (
AssertionError: Call paddle.distributed.init_parallel_env first to initialize the distributed environment.
"
paddle_distributed_communication_stream_alltoall.py,"C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\parallel.py:173: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  warnings.warn(
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_communication_stream_alltoall.py"", line 13, in <module>
    task = dist.stream.alltoall(out_tensor_list, [data1, data2], sync_op=False)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\communication\stream\alltoall.py"", line 148, in alltoall
    return _alltoall_in_dygraph(out_tensor_or_tensor_list,
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\communication\stream\alltoall.py"", line 54, in _alltoall_in_dygraph
    group = collective._get_default_group() if group is None else group
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 125, in _get_default_group
    assert is_initialized(), (
AssertionError: Call paddle.distributed.init_parallel_env first to initialize the distributed environment.
"
paddle_distributed_communication_stream_alltoall_single.py,"C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\parallel.py:173: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  warnings.warn(
W0330 20:51:29.868166 16252 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.1, Runtime API Version: 11.2
W0330 20:51:29.875169 16252 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_communication_stream_alltoall_single.py"", line 14, in <module>
    task = dist.stream.alltoall_single(output, data, sync_op=False)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\communication\stream\alltoall_single.py"", line 122, in alltoall_single
    return _alltoall_single_in_dygraph(out_tensor, in_tensor,
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\communication\stream\alltoall_single.py"", line 22, in _alltoall_single_in_dygraph
    group = collective._get_default_group() if group is None else group
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 125, in _get_default_group
    assert is_initialized(), (
AssertionError: Call paddle.distributed.init_parallel_env first to initialize the distributed environment.
"
paddle_distributed_communication_stream_all_gather.py,"C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\parallel.py:173: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  warnings.warn(
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_communication_stream_all_gather.py"", line 12, in <module>
    task = dist.stream.all_gather(tensor_list, data, sync_op=False)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\communication\stream\all_gather.py"", line 133, in all_gather
    return _all_gather_in_dygraph(tensor_or_tensor_list, tensor, group,
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\communication\stream\all_gather.py"", line 57, in _all_gather_in_dygraph
    group = collective._get_default_group() if group is None else group
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 125, in _get_default_group
    assert is_initialized(), (
AssertionError: Call paddle.distributed.init_parallel_env first to initialize the distributed environment.
"
paddle_distributed_communication_stream_all_reduce.py,"C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\parallel.py:173: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  warnings.warn(
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_communication_stream_all_reduce.py"", line 12, in <module>
    task = dist.stream.all_reduce(data, sync_op=False)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\communication\stream\all_reduce.py"", line 112, in all_reduce
    return _all_reduce_in_dygraph(tensor, op, group, sync_op,
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\communication\stream\all_reduce.py"", line 25, in _all_reduce_in_dygraph
    group = _get_global_group() if group is None else group
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\communication\group.py"", line 86, in _get_global_group
    raise RuntimeError(""The global group is not initialized."")
RuntimeError: The global group is not initialized.
"
paddle_distributed_communication_stream_broadcast.py,"C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\parallel.py:173: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  warnings.warn(
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_communication_stream_broadcast.py"", line 11, in <module>
    task = dist.stream.broadcast(data, src=1, sync_op=False)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\communication\stream\broadcast.py"", line 78, in broadcast
    return _broadcast_in_dygraph(tensor, src, group, sync_op,
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\communication\stream\broadcast.py"", line 20, in _broadcast_in_dygraph
    group = collective._get_default_group() if group is None else group
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 125, in _get_default_group
    assert is_initialized(), (
AssertionError: Call paddle.distributed.init_parallel_env first to initialize the distributed environment.
"
paddle_distributed_communication_stream_recv.py,"C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\parallel.py:173: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  warnings.warn(
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_communication_stream_recv.py"", line 9, in <module>
    task = dist.stream.send(data, dst=1, sync_op=False)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\communication\stream\send.py"", line 79, in send
    return _send_in_dygraph(tensor, dst, group, sync_op, use_calc_stream)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\communication\stream\send.py"", line 20, in _send_in_dygraph
    group = collective._get_default_group() if group is None else group
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 125, in _get_default_group
    assert is_initialized(), (
AssertionError: Call paddle.distributed.init_parallel_env first to initialize the distributed environment.
"
paddle_distributed_communication_stream_reduce.py,"C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\parallel.py:173: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  warnings.warn(
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_communication_stream_reduce.py"", line 11, in <module>
    task = dist.stream.reduce(data, dst=0, sync_op=False)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\communication\stream\reduce.py"", line 88, in reduce
    return _reduce_in_dygraph(tensor, dst, op, group, sync_op,
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\communication\stream\reduce.py"", line 22, in _reduce_in_dygraph
    group = _get_global_group() if group is None else group
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\communication\group.py"", line 86, in _get_global_group
    raise RuntimeError(""The global group is not initialized."")
RuntimeError: The global group is not initialized.
"
paddle_distributed_communication_stream_reduce_scatter.py,"C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\parallel.py:173: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  warnings.warn(
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_communication_stream_reduce_scatter.py"", line 12, in <module>
    dist.stream.reduce_scatter(data1, [data1, data2])
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\communication\stream\reduce_scatter.py"", line 144, in reduce_scatter
    return _reduce_scatter_in_dygraph(tensor, tensor_or_tensor_list, op,
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\communication\stream\reduce_scatter.py"", line 66, in _reduce_scatter_in_dygraph
    group = _get_global_group() if group is None else group
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\communication\group.py"", line 86, in _get_global_group
    raise RuntimeError(""The global group is not initialized."")
RuntimeError: The global group is not initialized.
"
paddle_distributed_communication_stream_scatter.py,"C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\parallel.py:173: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  warnings.warn(
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_communication_stream_scatter.py"", line 9, in <module>
    dist.stream.scatter(data1, src=1)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\communication\stream\scatter.py"", line 148, in scatter
    raise RuntimeError(""The input should be specified."")
RuntimeError: The input should be specified.
"
paddle_distributed_communication_stream_send.py,"C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\parallel.py:173: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  warnings.warn(
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_communication_stream_send.py"", line 9, in <module>
    task = dist.stream.send(data, dst=1, sync_op=False)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\communication\stream\send.py"", line 79, in send
    return _send_in_dygraph(tensor, dst, group, sync_op, use_calc_stream)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\communication\stream\send.py"", line 20, in _send_in_dygraph
    group = collective._get_default_group() if group is None else group
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 125, in _get_default_group
    assert is_initialized(), (
AssertionError: Call paddle.distributed.init_parallel_env first to initialize the distributed environment.
"
paddle_distributed_CountFilterEntry.py,"  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_CountFilterEntry.py"", line 11
    input=input,
         ^
SyntaxError: invalid syntax
"
paddle_distributed_destroy_process_group.py,"C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\parallel.py:173: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  warnings.warn(
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_destroy_process_group.py"", line 6, in <module>
    group = dist.new_group([0, 1])
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 384, in new_group
    global_group = _get_default_group()
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 125, in _get_default_group
    assert is_initialized(), (
AssertionError: Call paddle.distributed.init_parallel_env first to initialize the distributed environment.
"
paddle_distributed_fleet_utils_HDFSClient.py,"Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_fleet_utils_HDFSClient.py"", line 10, in <module>
    client.ls_dir(""hdfs:/test_hdfs_client"")
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\fleet\utils\fs.py"", line 407, in handler
    return f(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\fleet\utils\fs.py"", line 551, in ls_dir
    if not self.is_exist(fs_path):
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\fleet\utils\fs.py"", line 407, in handler
    return f(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\fleet\utils\fs.py"", line 689, in is_exist
    ret, out = self._run_cmd(cmd, redirect_stderr=True, retry_times=1)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\fleet\utils\fs.py"", line 482, in _run_cmd
    ret, output = core.shell_execute_cmd(exe_cmd, 0, 0, redirect_stderr)
NotImplementedError: (Unimplemented) This function(shell_get_command_output) is not implemented under _WIN32 or __APPLE__. (at ..\paddle\fluid\framework\io\shell.cc:373)

"
paddle_distributed_fleet_utils_recompute.py,"Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_fleet_utils_recompute.py"", line 76, in <module>
    loss_ref, param_ref, grad_ref = run_model(
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_fleet_utils_recompute.py"", line 55, in run_model
    model = Naive_fc_net(
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_fleet_utils_recompute.py"", line 34, in __init__
    self.runfunc0 = get_fc_block(0, input_size, is_last=False)
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_fleet_utils_recompute.py"", line 8, in get_fc_block
    (block_name + ""_fc_0"", paddle.nn.Linear(input_size, input_size, bias_attr=False)),
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\common.py"", line 160, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_distributed_get_group.py,"Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_get_group.py"", line 2, in <module>
    gid = paddle.distributed.new_group([2,4,6])
NameError: name 'paddle' is not defined
"
paddle_distributed_init_parallel_env.py,"C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\parallel.py:173: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  warnings.warn(
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_init_parallel_env.py"", line 40, in <module>
    dist.spawn(train)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\spawn.py"", line 606, in spawn
    while not context.join():
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\spawn.py"", line 413, in join
    self._throw_exception(error_index)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\spawn.py"", line 431, in _throw_exception
    raise Exception(msg)
Exception: 

----------------------------------------------
Process 0 terminated with the following error:
----------------------------------------------

Traceback (most recent call last):
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\spawn.py"", line 361, in _func_wrapper
    result = func(*args)
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_init_parallel_env.py"", line 21, in train
    layer = LinearNet()
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_init_parallel_env.py"", line 10, in __init__
    self._linear1 = nn.Linear(10, 10)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\common.py"", line 160, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)


"
paddle_distributed_irecv.py,"C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\parallel.py:173: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  warnings.warn(
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_irecv.py"", line 8, in <module>
    task = dist.isend(data, dst=1)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 1662, in isend
    group = _get_default_group() if group is None else group
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 125, in _get_default_group
    assert is_initialized(), (
AssertionError: Call paddle.distributed.init_parallel_env first to initialize the distributed environment.
"
paddle_distributed_isend.py,"C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\parallel.py:173: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  warnings.warn(
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_isend.py"", line 8, in <module>
    task = dist.isend(data, dst=1)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 1662, in isend
    group = _get_default_group() if group is None else group
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 125, in _get_default_group
    assert is_initialized(), (
AssertionError: Call paddle.distributed.init_parallel_env first to initialize the distributed environment.
"
paddle_distributed_new_group.py,"C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\parallel.py:173: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  warnings.warn(
W0330 20:54:36.446180 19124 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.1, Runtime API Version: 11.2
W0330 20:54:36.452179 19124 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_new_group.py"", line 5, in <module>
    gp = paddle.distributed.new_group([2,4,6])
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 384, in new_group
    global_group = _get_default_group()
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 125, in _get_default_group
    assert is_initialized(), (
AssertionError: Call paddle.distributed.init_parallel_env first to initialize the distributed environment.
"
paddle_distributed_ParallelEnv.py,"Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_ParallelEnv.py"", line 22, in <module>
    dist.spawn(train, nprocs=2)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\spawn.py"", line 574, in spawn
    procs_env_list = _get_subprocess_env_list(nprocs, options)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\spawn.py"", line 182, in _get_subprocess_env_list
    raise RuntimeError(
RuntimeError: the number of visible devices(1) is less than the number of spawn processes(2), please ensure that the correct `nprocs` argument is passed or the environment variable `CUDA_VISIBLE_DEVICES` is correctly configured.
"
paddle_distributed_ProbabilityEntry.py,"  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_ProbabilityEntry.py"", line 11
    input=input,
         ^
SyntaxError: invalid syntax
"
paddle_distributed_recv.py,"C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\parallel.py:173: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  warnings.warn(
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_recv.py"", line 8, in <module>
    dist.send(data, dst=1)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 1475, in send
    group = _get_default_group() if group is None else group
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 125, in _get_default_group
    assert is_initialized(), (
AssertionError: Call paddle.distributed.init_parallel_env first to initialize the distributed environment.
"
paddle_distributed_reduce.py,"C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\parallel.py:173: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  warnings.warn(
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_reduce.py"", line 10, in <module>
    dist.reduce(data, dst=0)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 787, in reduce
    group = _get_default_group() if group is None else group
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 125, in _get_default_group
    assert is_initialized(), (
AssertionError: Call paddle.distributed.init_parallel_env first to initialize the distributed environment.
"
paddle_distributed_ReduceOp.py,"C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\parallel.py:173: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  warnings.warn(
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_ReduceOp.py"", line 10, in <module>
    dist.all_reduce(data, op=dist.ReduceOp.SUM)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\communication\all_reduce.py"", line 61, in all_reduce
    return stream.all_reduce(tensor,
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\communication\stream\all_reduce.py"", line 112, in all_reduce
    return _all_reduce_in_dygraph(tensor, op, group, sync_op,
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\communication\stream\all_reduce.py"", line 25, in _all_reduce_in_dygraph
    group = _get_global_group() if group is None else group
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\communication\group.py"", line 86, in _get_global_group
    raise RuntimeError(""The global group is not initialized."")
RuntimeError: The global group is not initialized.
"
paddle_distributed_reduce_scatter.py,"C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\parallel.py:173: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  warnings.warn(
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_reduce_scatter.py"", line 12, in <module>
    dist.reduce_scatter(data1, [data1, data2])
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 1909, in reduce_scatter
    group = _get_default_group() if group is None else group
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 125, in _get_default_group
    assert is_initialized(), (
AssertionError: Call paddle.distributed.init_parallel_env first to initialize the distributed environment.
"
paddle_distributed_scatter.py,"C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\parallel.py:173: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  warnings.warn(
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_scatter.py"", line 9, in <module>
    dist.scatter(data1, src=1)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 1161, in scatter
    group = _get_default_group() if group is None else group
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 125, in _get_default_group
    assert is_initialized(), (
AssertionError: Call paddle.distributed.init_parallel_env first to initialize the distributed environment.
"
paddle_distributed_send.py,"C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\parallel.py:173: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  warnings.warn(
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_send.py"", line 8, in <module>
    dist.send(data, dst=1)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 1475, in send
    group = _get_default_group() if group is None else group
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 125, in _get_default_group
    assert is_initialized(), (
AssertionError: Call paddle.distributed.init_parallel_env first to initialize the distributed environment.
"
paddle_distributed_sharding_group_sharded_parallel.py,"[2023-03-30 20:55:37,736] [    INFO] topology.py:215 - HybridParallelInfo: rank_id: 0, mp_degree: 1, sharding_degree: 1, pp_degree: 1, dp_degree: 1, mp_group: [0],  sharding_group: [0], pp_group: [0], dp_group: [0], check/clip group: [0]
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_sharding_group_sharded_parallel.py"", line 8, in <module>
    group = paddle.distributed.new_group([0, 1])
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 384, in new_group
    global_group = _get_default_group()
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 125, in _get_default_group
    assert is_initialized(), (
AssertionError: Call paddle.distributed.init_parallel_env first to initialize the distributed environment.
"
paddle_distributed_sharding_save_group_sharded_model.py,"[2023-03-30 20:55:42,932] [    INFO] topology.py:215 - HybridParallelInfo: rank_id: 0, mp_degree: 1, sharding_degree: 1, pp_degree: 1, dp_degree: 1, mp_group: [0],  sharding_group: [0], pp_group: [0], dp_group: [0], check/clip group: [0]
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_sharding_save_group_sharded_model.py"", line 8, in <module>
    group = paddle.distributed.new_group([0, 1])
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 384, in new_group
    global_group = _get_default_group()
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 125, in _get_default_group
    assert is_initialized(), (
AssertionError: Call paddle.distributed.init_parallel_env first to initialize the distributed environment.
"
paddle_distributed_spawn.py,"C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\parallel.py:173: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  warnings.warn(
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_spawn.py"", line 48, in <module>
    dist.spawn(train)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\spawn.py"", line 606, in spawn
    while not context.join():
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\spawn.py"", line 413, in join
    self._throw_exception(error_index)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\spawn.py"", line 431, in _throw_exception
    raise Exception(msg)
Exception: 

----------------------------------------------
Process 0 terminated with the following error:
----------------------------------------------

Traceback (most recent call last):
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\spawn.py"", line 361, in _func_wrapper
    result = func(*args)
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_spawn.py"", line 23, in train
    layer = LinearNet()
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_spawn.py"", line 11, in __init__
    self._linear1 = nn.Linear(10, 10)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\common.py"", line 160, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)


"
paddle_distributed_split.py,"Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_split.py"", line 9, in <module>
    emb_out = paddle.distributed.split(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\fleet\layers\mpu\mp_ops.py"", line 748, in split
    emb_out = _parallel_embedding(x,
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\fleet\layers\mpu\mp_ops.py"", line 571, in _parallel_embedding
    output_parallel = _c_lookup_table(weight,
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\fleet\layers\mpu\mp_ops.py"", line 278, in _c_lookup_table
    helper.append_op(type='c_embedding',
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper.py"", line 45, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 4040, in append_op
    op = Operator(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 2890, in __init__
    proto = OpProtoHolder.instance().get_op_proto(type)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 2713, in get_op_proto
    raise ValueError(""Operator \""%s\"" has not been registered."" % type)
ValueError: Operator ""c_embedding"" has not been registered.
"
paddle_distributed_wait.py,"C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\parallel.py:173: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  warnings.warn(
W0330 20:56:08.973606 11036 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.1, Runtime API Version: 11.2
W0330 20:56:08.979602 11036 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distributed_wait.py"", line 5, in <module>
    paddle.distributed.all_reduce(tindata, sync_op=True)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\communication\all_reduce.py"", line 61, in all_reduce
    return stream.all_reduce(tensor,
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\communication\stream\all_reduce.py"", line 112, in all_reduce
    return _all_reduce_in_dygraph(tensor, op, group, sync_op,
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\communication\stream\all_reduce.py"", line 25, in _all_reduce_in_dygraph
    group = _get_global_group() if group is None else group
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\communication\group.py"", line 86, in _get_global_group
    raise RuntimeError(""The global group is not initialized."")
RuntimeError: The global group is not initialized.
"
paddle_distribution_Normal.py,"Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distribution_Normal.py"", line 5, in <module>
    dist = Normal(loc=0., scale=3.)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distribution\normal.py"", line 146, in __init__
    self.loc, self.scale = self._to_tensor(loc, scale)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distribution\distribution.py"", line 224, in _to_tensor
    arg_variable = tensor.create_tensor(dtype=dtype)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layers\tensor.py"", line 93, in create_tensor
    return helper.create_variable(name=helper.name,
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 441, in create_variable
    return self.main_program.current_block().create_var(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3834, in create_var
    var = _varbase_creator(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 1297, in _varbase_creator
    eager_tensor = core.eager.Tensor(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_distribution_TransformedDistribution.py,"Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distribution_TransformedDistribution.py"", line 5, in <module>
    paddle.distribution.Normal(0., 1.),
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distribution\normal.py"", line 146, in __init__
    self.loc, self.scale = self._to_tensor(loc, scale)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distribution\distribution.py"", line 224, in _to_tensor
    arg_variable = tensor.create_tensor(dtype=dtype)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layers\tensor.py"", line 93, in create_tensor
    return helper.create_variable(name=helper.name,
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 441, in create_variable
    return self.main_program.current_block().create_var(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3834, in create_var
    var = _varbase_creator(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 1297, in _varbase_creator
    eager_tensor = core.eager.Tensor(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_distribution_Uniform.py,"Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_distribution_Uniform.py"", line 5, in <module>
    u1 = Uniform(low=3.0, high=4.0)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distribution\uniform.py"", line 153, in __init__
    self.low, self.high = self._to_tensor(low, high)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distribution\distribution.py"", line 224, in _to_tensor
    arg_variable = tensor.create_tensor(dtype=dtype)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layers\tensor.py"", line 93, in create_tensor
    return helper.create_variable(name=helper.name,
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 441, in create_variable
    return self.main_program.current_block().create_var(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3834, in create_var
    var = _varbase_creator(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 1297, in _varbase_creator
    eager_tensor = core.eager.Tensor(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_flops.py,"Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_flops.py"", line 33, in <module>
    lenet = LeNet()
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_flops.py"", line 9, in __init__
    nn.Conv2D(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\conv.py"", line 687, in __init__
    super(Conv2D, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\conv.py"", line 157, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_hub_load.py,"Using cache found in C:\Users\phalt\.cache\paddle\hub\lyuwenyu_paddlehub_demo_main
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_hub_load.py"", line 2, in <module>
    paddle.hub.load('lyuwenyu/paddlehub_demo:main', model='MM', source='github')
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\hapi\hub.py"", line 302, in load
    return entry(**kwargs)
  File ""C:\Users\phalt\.cache\paddle\hub\lyuwenyu_paddlehub_demo_main\hubconf.py"", line 10, in MM
    mm = _MM(out_channels)
  File ""C:\Users\phalt\.cache\paddle\hub\lyuwenyu_paddlehub_demo_main\model.py"", line 8, in __init__
    self.conv = nn.Conv2D(3, out_channels, 3, 2, 1)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\conv.py"", line 687, in __init__
    super(Conv2D, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\conv.py"", line 157, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_incubate_nn_FusedFeedForward.py,"Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_incubate_nn_FusedFeedForward.py"", line 5, in <module>
    fused_feedforward_layer = FusedFeedForward(8, 8)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\incubate\nn\layer\fused_transformer.py"", line 590, in __init__
    self._linear1_weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_incubate_nn_FusedLinear.py,"W0330 21:07:23.040257  9404 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.1, Runtime API Version: 11.2
W0330 21:07:23.046257  9404 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_incubate_nn_FusedLinear.py"", line 6, in <module>
    linear = FusedLinear(4, 5)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\incubate\nn\layer\fused_linear.py"", line 82, in __init__
    self.weight = self.create_parameter(shape=weight_shape,
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_incubate_nn_FusedMultiHeadAttention.py,"W0330 21:07:29.669215  3340 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.1, Runtime API Version: 11.2
W0330 21:07:29.674213  3340 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_incubate_nn_FusedMultiHeadAttention.py"", line 7, in <module>
    multi_head_attn = paddle.incubate.nn.FusedMultiHeadAttention(128, 2)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\incubate\nn\layer\fused_transformer.py"", line 321, in __init__
    self.qkv_weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_incubate_nn_FusedMultiTransformer.py,"W0330 21:07:35.786177 19156 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.1, Runtime API Version: 11.2
W0330 21:07:35.791173 19156 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_incubate_nn_FusedMultiTransformer.py"", line 9, in <module>
    encoder_layers = FusedMultiTransformer(128, 2, 512, num_layers=1)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\incubate\nn\layer\fused_transformer.py"", line 1262, in __init__
    ln_scale = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_incubate_nn_FusedTransformerEncoderLayer.py,"W0330 21:07:41.829138 22328 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.1, Runtime API Version: 11.2
W0330 21:07:41.834136 22328 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_incubate_nn_FusedTransformerEncoderLayer.py"", line 9, in <module>
    encoder_layer = FusedTransformerEncoderLayer(128, 2, 512)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\incubate\nn\layer\fused_transformer.py"", line 810, in __init__
    self.fused_attn = FusedMultiHeadAttention(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\incubate\nn\layer\fused_transformer.py"", line 321, in __init__
    self.qkv_weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_incubate_xpu_resnet_block_ResNetBasicBlock.py,"W0330 21:08:41.007769 23948 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.1, Runtime API Version: 11.2
W0330 21:08:41.016769 23948 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_incubate_xpu_resnet_block_ResNetBasicBlock.py"", line 8, in <module>
    resnet_basic_block = ResNetBasicBlock(num_channels1=ch_in,
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\incubate\xpu\resnet_block.py"", line 547, in __init__
    self.filter_1 = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_io_DataLoader.py,"  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_io_DataLoader.py"", line 2
    For reading iterable dataset with multiprocess Dataloader, please see paddle.io.IterableDataset
        ^
SyntaxError: invalid syntax
"
paddle_jit_to_static.py,"W0330 21:10:49.296092 16388 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.1, Runtime API Version: 11.2
W0330 21:10:49.304088 16388 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py"", line 397, in __call__
    return partial_program_layer(args)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\dygraph_to_static\partial_program.py"", line 595, in __call__
    in_vars, out_vars = self._prepare(inputs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\dygraph_to_static\partial_program.py"", line 852, in _prepare
    out_vars = list(map(create_out, self._outputs.var_ids))
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\dygraph_to_static\partial_program.py"", line 840, in create_out
    var_base = core.eager.Tensor(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_jit_to_static.py"", line 13, in <module>
    x_v = func(x)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py"", line 406, in __call__
    error_data.raise_new_exception()
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\dygraph_to_static\error.py"", line 341, in raise_new_exception
    new_exception = self.create_exception()
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\dygraph_to_static\error.py"", line 165, in create_exception
    message = self.create_message()
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\dygraph_to_static\error.py"", line 189, in create_message
    self._simplify_error_value()
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\dygraph_to_static\error.py"", line 274, in _simplify_error_value
    start_idx = error_value_lines_strip.index(start_trace)
ValueError: 'outputs = static_func(*inputs)' is not in list
"
paddle_jit_TranslatedLayer.py,"Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_jit_TranslatedLayer.py"", line 49, in <module>
    layer = LinearNet()
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_jit_TranslatedLayer.py"", line 29, in __init__
    self._linear = nn.Linear(IMAGE_SIZE, CLASS_NUM)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\common.py"", line 160, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_load.py,"Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_load.py"", line 3, in <module>
    emb = paddle.nn.Embedding(10, 10)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\common.py"", line 1505, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_Model.py,"Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_Model.py"", line 31, in <module>
    run_example_code()
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_Model.py"", line 9, in run_example_code
    net = nn.Sequential(nn.Flatten(1), nn.Linear(784, 200), nn.Tanh(),
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\common.py"", line 160, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_nanmedian.py,"Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_nanmedian.py"", line 4, in <module>
    y1 = x.nanmedian()
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\tensor\stat.py"", line 365, in nanmedian
    out = helper.create_variable_for_type_inference(x.dtype)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 404, in create_variable_for_type_inference
    return self.main_program.current_block().create_var(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3834, in create_var
    var = _varbase_creator(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 1297, in _varbase_creator
    eager_tensor = core.eager.Tensor(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_nn_BatchNorm1D.py,"W0330 21:18:22.644073 12208 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.1, Runtime API Version: 11.2
W0330 21:18:22.650072 12208 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_nn_BatchNorm1D.py"", line 4, in <module>
    batch_norm = paddle.nn.BatchNorm1D(1)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\norm.py"", line 823, in __init__
    super(BatchNorm1D, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\norm.py"", line 630, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_nn_BatchNorm2D.py,"W0330 21:18:28.369046 10216 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.1, Runtime API Version: 11.2
W0330 21:18:28.375046 10216 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_nn_BatchNorm2D.py"", line 4, in <module>
    batch_norm = paddle.nn.BatchNorm2D(1)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\norm.py"", line 630, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_nn_BatchNorm3D.py,"W0330 21:18:34.113021 23624 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.1, Runtime API Version: 11.2
W0330 21:18:34.118021 23624 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_nn_BatchNorm3D.py"", line 4, in <module>
    batch_norm = paddle.nn.BatchNorm3D(1)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\norm.py"", line 1021, in __init__
    super(BatchNorm3D, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\norm.py"", line 630, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_nn_BeamSearchDecoder.py,"Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_nn_BeamSearchDecoder.py"", line 5, in <module>
    trg_embeder = Embedding(100, 32)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\common.py"", line 1505, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_nn_Bilinear.py,"W0330 21:18:56.609923  9784 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.1, Runtime API Version: 11.2
W0330 21:18:56.614923  9784 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_nn_Bilinear.py"", line 5, in <module>
    bilinear = paddle.nn.Bilinear(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\common.py"", line 673, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_nn_BiRNN.py,"Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_nn_BiRNN.py"", line 3, in <module>
    cell_fw = paddle.nn.LSTMCell(16, 32)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\rnn.py"", line 505, in __init__
    self.weight_ih = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_nn_ClipGradByGlobalNorm.py,"W0330 21:19:18.864823 13064 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.1, Runtime API Version: 11.2
W0330 21:19:18.869819 13064 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_nn_ClipGradByGlobalNorm.py"", line 4, in <module>
    linear = paddle.nn.Linear(in_features=10, out_features=10,
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\common.py"", line 160, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_nn_ClipGradByNorm.py,"W0330 21:19:24.628796  7724 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.1, Runtime API Version: 11.2
W0330 21:19:24.634796  7724 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_nn_ClipGradByNorm.py"", line 4, in <module>
    linear = paddle.nn.Linear(in_features=10, out_features=10,
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\common.py"", line 160, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_nn_ClipGradByValue.py,"W0330 21:19:30.377771 21132 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.1, Runtime API Version: 11.2
W0330 21:19:30.383772 21132 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_nn_ClipGradByValue.py"", line 4, in <module>
    linear = paddle.nn.Linear(in_features=10, out_features=10,
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\common.py"", line 160, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_nn_Conv1D.py,"Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_nn_Conv1D.py"", line 14, in <module>
    conv = Conv1D(3, 2, 3)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\conv.py"", line 348, in __init__
    super(Conv1D, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\conv.py"", line 157, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_nn_Conv1DTranspose.py,"Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_nn_Conv1DTranspose.py"", line 11, in <module>
    conv = Conv1DTranspose(2, 1, 2)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\conv.py"", line 530, in __init__
    super(Conv1DTranspose, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\conv.py"", line 157, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_nn_Conv2D.py,"W0330 21:19:48.007692 23780 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.1, Runtime API Version: 11.2
W0330 21:19:48.012688 23780 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_nn_Conv2D.py"", line 8, in <module>
    conv = nn.Conv2D(4, 6, (3, 3))
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\conv.py"", line 687, in __init__
    super(Conv2D, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\conv.py"", line 157, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_nn_Conv2DTranspose.py,"W0330 21:19:53.728668 23852 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.1, Runtime API Version: 11.2
W0330 21:19:53.734663 23852 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_nn_Conv2DTranspose.py"", line 8, in <module>
    conv = nn.Conv2DTranspose(4, 6, (3, 3))
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\conv.py"", line 860, in __init__
    super(Conv2DTranspose, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\conv.py"", line 157, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_nn_Conv3D.py,"W0330 21:19:59.443637 23944 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.1, Runtime API Version: 11.2
W0330 21:19:59.448642 23944 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_nn_Conv3D.py"", line 8, in <module>
    conv = nn.Conv3D(4, 6, (3, 3, 3))
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\conv.py"", line 1018, in __init__
    super(Conv3D, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\conv.py"", line 157, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_nn_Conv3DTranspose.py,"W0330 21:20:05.215611 15732 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.1, Runtime API Version: 11.2
W0330 21:20:05.221613 15732 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_nn_Conv3DTranspose.py"", line 8, in <module>
    conv = nn.Conv3DTranspose(4, 6, (3, 3, 3))
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\conv.py"", line 1199, in __init__
    super(Conv3DTranspose, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\conv.py"", line 157, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_nn_CosineSimilarity.py,"  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_nn_CosineSimilarity.py"", line 1
    Case 0:
         ^
SyntaxError: invalid syntax
"
paddle_nn_dynamic_decode.py,"Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_nn_dynamic_decode.py"", line 5, in <module>
    trg_embeder = Embedding(100, 32)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\common.py"", line 1505, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_nn_functional_class_center_sample.py,"[2023-03-30 21:21:14,694] [    INFO] topology.py:215 - HybridParallelInfo: rank_id: 0, mp_degree: 1, sharding_degree: 1, pp_degree: 1, dp_degree: 1, mp_group: [0],  sharding_group: [0], pp_group: [0], dp_group: [0], check/clip group: [0]
W0330 21:21:16.464294  2836 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.1, Runtime API Version: 11.2
W0330 21:21:16.469293  2836 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_nn_functional_class_center_sample.py"", line 15, in <module>
    dist.all_gather(label_list, label)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 946, in all_gather
    group = _get_default_group() if group is None else group
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 125, in _get_default_group
    assert is_initialized(), (
AssertionError: Call paddle.distributed.init_parallel_env first to initialize the distributed environment.
"
paddle_nn_functional_cosine_similarity.py,"  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_nn_functional_cosine_similarity.py"", line 1
    Case 0:
         ^
SyntaxError: invalid syntax
"
paddle_nn_functional_margin_cross_entropy.py,"[2023-03-30 21:23:50,553] [    INFO] topology.py:215 - HybridParallelInfo: rank_id: 0, mp_degree: 1, sharding_degree: 1, pp_degree: 1, dp_degree: 1, mp_group: [0],  sharding_group: [0], pp_group: [0], dp_group: [0], check/clip group: [0]
W0330 21:23:52.290591  7200 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.1, Runtime API Version: 11.2
W0330 21:23:52.295593  7200 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_nn_functional_margin_cross_entropy.py"", line 19, in <module>
    dist.all_gather(label_list, label)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 946, in all_gather
    group = _get_default_group() if group is None else group
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\distributed\collective.py"", line 125, in _get_default_group
    assert is_initialized(), (
AssertionError: Call paddle.distributed.init_parallel_env first to initialize the distributed environment.
"
paddle_nn_functional_normalize.py,"W0330 21:25:05.255265  3736 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.1, Runtime API Version: 11.2
W0330 21:25:05.260260  3736 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_nn_functional_normalize.py"", line 6, in <module>
    y = F.normalize(x)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\functional\norm.py"", line 89, in normalize
    eps = fluid.dygraph.base.to_variable([epsilon], dtype=x.dtype)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\base.py"", line 794, in to_variable
    return core.eager.Tensor(value, framework._current_expected_place(),
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 6 position args and the remainting arguments are kwargs. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:887)

"
paddle_nn_functional_pairwise_distance.py,"W0330 21:25:31.187147 18868 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.1, Runtime API Version: 11.2
W0330 21:25:31.192147 18868 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_nn_functional_pairwise_distance.py"", line 4, in <module>
    distance = paddle.nn.functional.pairwise_distance(x, y)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\functional\distance.py"", line 75, in pairwise_distance
    epsilon = paddle.fluid.dygraph.base.to_variable([epsilon],
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\base.py"", line 794, in to_variable
    return core.eager.Tensor(value, framework._current_expected_place(),
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 6 position args and the remainting arguments are kwargs. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:887)

"
paddle_nn_functional_triplet_margin_loss.py,"W0330 21:26:24.031910 19272 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.1, Runtime API Version: 11.2
W0330 21:26:24.036911 19272 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_nn_functional_triplet_margin_loss.py"", line 7, in <module>
    loss = F.triplet_margin_loss(input, positive, negative, margin=1.0, reduction='none')
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\functional\loss.py"", line 3790, in triplet_margin_loss
    positive_dist = distance_function(input, positive)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 103, in new_call
    outputs = old_call(self, *inputs, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 103, in new_call
    outputs = old_call(self, *inputs, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\distance.py"", line 72, in forward
    return F.pairwise_distance(x, y, self.p, self.epsilon, self.keepdim,
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\functional\distance.py"", line 75, in pairwise_distance
    epsilon = paddle.fluid.dygraph.base.to_variable([epsilon],
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\base.py"", line 794, in to_variable
    return core.eager.Tensor(value, framework._current_expected_place(),
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 6 position args and the remainting arguments are kwargs. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:887)

"
paddle_nn_functional_triplet_margin_with_distance_loss.py,"W0330 21:26:29.984879 21804 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.1, Runtime API Version: 11.2
W0330 21:26:29.989883 21804 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_nn_functional_triplet_margin_with_distance_loss.py"", line 7, in <module>
    loss = F.triplet_margin_with_distance_loss(input, positive, negative, margin=1.0, reduction='none')
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\functional\loss.py"", line 3655, in triplet_margin_with_distance_loss
    positive_dist = distance_function(input, positive)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 103, in new_call
    outputs = old_call(self, *inputs, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 103, in new_call
    outputs = old_call(self, *inputs, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\distance.py"", line 72, in forward
    return F.pairwise_distance(x, y, self.p, self.epsilon, self.keepdim,
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_func.py"", line 99, in wrapper
    outputs = func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\functional\distance.py"", line 75, in pairwise_distance
    epsilon = paddle.fluid.dygraph.base.to_variable([epsilon],
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\base.py"", line 794, in to_variable
    return core.eager.Tensor(value, framework._current_expected_place(),
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 6 position args and the remainting arguments are kwargs. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:887)

"
paddle_nn_GroupNorm.py,"W0330 21:26:57.364768 15124 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.1, Runtime API Version: 11.2
W0330 21:26:57.369768 15124 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_nn_GroupNorm.py"", line 4, in <module>
    group_norm = paddle.nn.GroupNorm(num_channels=6, num_groups=6)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\norm.py"", line 390, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_nn_GRU.py,"Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_nn_GRU.py"", line 3, in <module>
    rnn = paddle.nn.GRU(16, 32, 2)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\rnn.py"", line 1441, in __init__
    super(GRU,
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\rnn.py"", line 915, in __init__
    cell = rnn_cls(input_size, hidden_size, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\rnn.py"", line 656, in __init__
    self.weight_ih = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_nn_GRUCell.py,"W0330 21:27:08.208737  5052 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.1, Runtime API Version: 11.2
W0330 21:27:08.214738  5052 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_nn_GRUCell.py"", line 6, in <module>
    cell = paddle.nn.GRUCell(16, 32)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\rnn.py"", line 656, in __init__
    self.weight_ih = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_nn_HSigmoidLoss.py,"Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_nn_HSigmoidLoss.py"", line 10, in <module>
    m = paddle.nn.HSigmoidLoss(3, 5)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\loss.py"", line 501, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_nn_initializer_Assign.py,"W0330 21:27:58.717584  2340 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.1, Runtime API Version: 11.2
W0330 21:27:58.724583  2340 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_nn_initializer_Assign.py"", line 12, in <module>
    linear_1 = paddle.nn.Linear(2, 2, weight_attr=weight_attr_1, bias_attr=bias_attr_1)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\common.py"", line 160, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_nn_initializer_Constant.py,"W0330 21:28:10.019551 18580 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.1, Runtime API Version: 11.2
W0330 21:28:10.025550 18580 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_nn_initializer_Constant.py"", line 5, in <module>
    linear = nn.Linear(2,
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\common.py"", line 160, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_nn_LSTM.py,"Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_nn_LSTM.py"", line 3, in <module>
    rnn = paddle.nn.LSTM(16, 32, 2)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\rnn.py"", line 1333, in __init__
    super(LSTM,
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\rnn.py"", line 915, in __init__
    cell = rnn_cls(input_size, hidden_size, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\rnn.py"", line 505, in __init__
    self.weight_ih = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_nn_LSTMCell.py,"W0330 21:28:43.136441  1324 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.1, Runtime API Version: 11.2
W0330 21:28:43.141441  1324 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_nn_LSTMCell.py"", line 7, in <module>
    cell = paddle.nn.LSTMCell(16, 32)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\rnn.py"", line 505, in __init__
    self.weight_ih = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_NPUPlace.py,"  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_NPUPlace.py"", line 1
    System Message: ERROR/3 (docstring of paddle.fluid.libpaddle.NPUPlace, line 6)
           ^
SyntaxError: invalid syntax
"
paddle_optimizer_lr_InverseTimeDecay.py,"Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_optimizer_lr_InverseTimeDecay.py"", line 5, in <module>
    linear = paddle.nn.Linear(10, 10)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\common.py"", line 160, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_ParamAttr.py,"Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_ParamAttr.py"", line 8, in <module>
    paddle.nn.Linear(3, 4, weight_attr=weight_attr)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\common.py"", line 160, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_save.py,"Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_save.py"", line 3, in <module>
    emb = paddle.nn.Embedding(10, 10)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\common.py"", line 1505, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
paddle_summary.py,"Traceback (most recent call last):
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_summary.py"", line 33, in <module>
    lenet = LeNet()
  File ""E:\UIUC\Spring 2023\CS 527\FreeFuzz\Scrape\api_documentation_code\paddle_summary.py"", line 9, in __init__
    nn.Conv2D(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\conv.py"", line 687, in __init__
    super(Conv2D, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\nn\layer\conv.py"", line 157, in __init__
    self.weight = self.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\dygraph\layers.py"", line 471, in create_parameter
    return self._helper.create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\layer_helper_base.py"", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 3948, in create_parameter
    param = EagerParamBase(*args, **kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\decorator.py"", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\wrapped_decorator.py"", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 534, in __impl__
    return func(*args, **kwargs)
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\framework.py"", line 7197, in __init__
    super(EagerParamBase, self).__init__(
  File ""C:\Users\phalt\AppData\Roaming\Python\Python39\site-packages\paddle\decorate_cls.py"", line 98, in new_init
    old_init(self, *args, **kwargs)
ValueError: (InvalidArgument) Incompatible constructor arguments, there are 5 position args and remainting arguments are kwargs,but the first position args should be PyArray. Please check your code and make sure the first position args is PyArray. (at ..\paddle\fluid\pybind\eager.cc:871)

"
